### ISSUE TITLE
To detect Arduino correctly in C++

### ISSUE THREAD

**Issue by georgy7** [vinmenn/Crc16#3]
How are you, Vincenzo?
I am glad to see such compact C++ library, calculating CRC16.
I would use it in my compressing app. I plan to use this library on desktop.
There is the code with `WProgram.h`. And there is no such file on the most of envieronments.

```
#if defined(ARDUINO) && ARDUINO >= 100
  #include "Arduino.h"
#else
  #include "WProgram.h"
#endif
```

Could you please correct me. Is this the right way to detect Arduino or not?

```
#if defined(ARDUINO) && ARDUINO >= 100
  #include "Arduino.h"
#elif defined(ARDUINO)
  #include "WProgram.h"
#else
  // Includes for other platforms.
#endif
```

**Comment by vinmenn** [comment]
Hi, thanks for interest in my library.

Wprogram.h and arduino.h are standard include files installed by default
with ide, the first for compatibility with older versions.
Currently I'm not up-to-date with last version of Arduino ide, maybe
wprogram was eliminated in last version of software.
Try to eliminate wprogram.h and use directly Arduino.h
Hope it helps
Best regards
Vincenzo

Il gio 19 apr 2018, 16:03 Георгий У. <notifications@github.com> ha scritto:

**Comment by per1234** [comment]
>Is this the right way to detect Arduino or not?

Should work.
>I'm not up-to-date with last version of Arduino ide, maybe wprogram was eliminated in last version of software.

I guess you're pretty far out of date. WProgram.h was renamed Arduino.h before the Arduino IDE 1.0.0 release, 7 years ago: https://github.com/arduino/Arduino/commit/d05e4021d04624100bc54809aa508aaa8f90f0d0

**Comment by georgy7** [comment]
No, no. I think, I did not explain clearly enough.
I plan to use it on *non-Arduino* platform. Pure C++. On Windows and Linux. With GCC, Clang or DigitalMars C++ Compiler. So, I must include `cstdint`, `cstdlib` and so on, instead of `WProgram.h` or `Arduino.h`. That's why I asked, is `defined(ARDUINO)` true on all Arduino versions.

**Comment by georgy7** [comment]
> Should work.

Thanks 🙂

**Comment by vinmenn** [comment]
Yes you're right, that form was used during the transition with first
"official" versions, now it's useless, but i continued to use old form, btw
if you search inside arduino libraries there are other examples...
Currently I'm using version 1.6.12, not the last but it works...
Bye

2018-04-20 10:56 GMT+02:00 per1234 <notifications@github.com>:
