### ISSUE TITLE
Need help with CRC-16/MCRF4XX

### ISSUE THREAD

**Issue by ChrisFredriksson** [vinmenn/Crc16#5]
Hi there,
Just found this project as I'm looking for an Arduino based CRC16 library and this seems to be the one I should use - as it is customizable to use several CRC16 types.

I'm looking into using MCRF4XX but I can't really get it to work.

Looking at the XModemCrc function description;
```
    inline unsigned int XModemCrc(uint8_t data[], uint8_t start, uint16_t length)
    {
        //  XModem parameters: poly=0x1021 init=0x0000 refin=false refout=false xorout=0x0000
        return fastCrc(data, start, length, false, false, 0x1021, 0x0000, 0x0000, 0x8000, 0xffff);
    }
```

.. I thought I would copy that and make my own for MCRF4XX like so;
```
    inline unsigned int MCRF4XXCrc(uint8_t data[], uint8_t start, uint16_t length)
    {
        //  MCRF4XX parameters: poly=0x1021 init=0xFFFF refin=true refout=true xorout=0x0000
        return fastCrc(data, start, length, true, true, 0x1021, 0x0000, 0x0000, 0x8000, 0xffff);
    }
```
.. but it doesn't seem to work, or well it doesn't work.

So, obviously I'm doing something wrong. I found this page that describes the specs for this CRC type;
https://crccalc.com/ - clicking "Calc CRC-16" reveals the bigger list with MFRC4XX in it.

MCRF4XX has the following specs;
Poly 0x1021 (same as XModem)
RefIn true (easy change)
RefOut true (easy change)
XorOut 0x0000 (same as XModem)

But then we get to Init which is different. 0x0000 for XModem and 0xFFFF for MCRF4XX.

In the comment above the function description XModem has init=0x0000, but I can't relate to which value this would be in the actual function? Of course, there are two sets of 0x0000 and I've tried changing both to 0xFFFF, one at a time, with no positive results.

All I get out is 0 from the function, nothing more, nothing less.

So all I really changed is the function name and refin/refout to true.

Original function call;
```
    byte GPIO0off[5]            = { 0x06, 0x0B, 0x00, 0x01, 0x00 };
    uint8_t sizeOfVar = sizeof(GPIO0off);
    
    value = crc.XModemCrc(GPIO0off,0,sizeOfVar);
    mySerial.print("crc = 0x");    
    mySerial.println(value, HEX);
```

My new function call;
```
	byte GPIO0off[5]            = { 0x06, 0x0B, 0x00, 0x01, 0x00 };
	uint8_t sizeOfVar = sizeof(GPIO0off);
	
	value = crc.MCRF4XXCrc(GPIO0off,0,sizeOfVar);
	Serial.print("crc = 0x");    
	Serial.println(value, HEX);
```

Could I ask for some help on this? Many thanks in advance :)

**Comment by vinmenn** [comment]
Hi,
I can't check directly on Arduino now but i think that you should use these
parameters for MCRF4XX:

inline unsigned int MCRF4XXCrc(uint8_t data[], uint8_t start, uint16_t
length)
{
  // MCRF4XX parameters: poly=0x1021 init=0xFFFF refin=true refout=true
xorout=0x0000
  // CRC-16/MCRF4XX 0x6F91 0x6F91 0x1021 0xFFFF true true 0x0000
  return fastCrc(data, start, length, true, true, 0x1021, *0xffff*, 0x0000,
0x8000, 0xffff);
}
Assuming parameters indicated on https://crccalc.com/ seems that xorIn
should be 0xffff instead of 0x0000.
try passing "123456789" as byte array and check for result equal to 0x6F91 as
indicated on crccalc site

Hope this helps

Vincenzo


Il giorno mer 5 giu 2019 alle ore 16:19 ChrisFredriksson <
notifications@github.com> ha scritto:

**Comment by vinmenn** [comment]
Hi Chris,
Yesterday I checked with an arduino and effectively there was a bug in
reflect routine for reflect out parameter set to true.
I updated library to 0.1.2 and now works with Mcrf4xx parameters and in
general with all settings with refout = true.
For your convenience I put Mcrf4xx setting as inline function so you can
use straightly.
Thanks for your signalation
Best regards
Vincenzo Mennella

Il giorno mer 5 giu 2019 alle ore 17:09 Vincenzo M. <vinmen11@gmail.com> ha
scritto:

**Comment by ChrisFredriksson** [comment]
That seems to work very well, Thank you! :)
